# Generated by Django 4.2.29 on 2026-03-11 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('inspected_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'OFFICER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_messages', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'receiver'], name='core_messag_sender__2a6008_idx'), models.Index(fields=['created_at'], name='core_messag_created_a655d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_prisoners', to=settings.AUTH_USER_MODEL)),
                ('prisoner', models.ForeignKey(limit_choices_to={'role': 'PRISONER'}, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'prisoner'], name='core_custom_custome_fa1e32_idx')],
                'unique_together': {('customer', 'prisoner')},
            },
        ),
    ]
