# Generated by Django 4.2.29 on 2026-03-11 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipients_and_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='thread',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='threads_as_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='prisoner',
            field=models.ForeignKey(limit_choices_to={'role': 'PRISONER'}, on_delete=django.db.models.deletion.CASCADE, related_name='threads_as_prisoner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.thread'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread'], name='core_messag_thread__2881a4_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['customer', 'prisoner'], name='core_thread_custome_0ce83d_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['-updated_at'], name='core_thread_updated_e17318_idx'),
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.UniqueConstraint(fields=('customer', 'prisoner'), name='core_thread_customer_prisoner_uniq'),
        ),
    ]
