# Generated by Django 4.2.29 on 2026-03-12 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message_thread_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prisoner_number',
            field=models.CharField(blank=True, help_text='UK MoJ-style prisoner number (e.g. AB1234 or A1417AE). Only for prisoners.', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([A-Z]{2}[0-9]{4}|[A-Z][0-9]{4}[A-Z]{2})$', code='invalid_prisoner_number', message='Enter a valid UK prisoner number (e.g. AB1234 or A1417AE).')]),
        ),
    ]
