# Generated by Django 4.2.29 on 2026-03-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_prison_and_scope'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='thread',
            new_name='core_thread_prison__5964f3_idx',
            old_name='core_thread_prison__a1b2c3_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When the receiver viewed the thread (read receipt).', null=True),
        ),
    ]
